### ISSUE TITLE
密码问题

### ISSUE THREAD

**Issue by 865102930** [StanleyCocos/gesture_password#1]
返回的结果是个数组,我正着连接返回的是顺序数组[密码,0-9],反着连接返回的也是顺序数组[密码0-9, 其实真实密码是9-0],密码其实不一样的. 0和3从中间空隙连接中间其实走2的.2没有进入数组.

**Comment by StanleyCocos** [comment]
不好意思  我才看到这个问题  之前我也发现这个问题了 并且修复了 感谢你
